#!/usr/bin/perl -w
use strict;
use warnings;

my $inputFile = $ARGV[0];
my $outputFile = $ARGV[1];

my $title = "";
my $author = "";
my $key = "";
my @fields;
my @words;

open my $fh, '<', $inputFile or die "error opening $inputFile: $!";
my $data = do { local $/; <$fh> };
close $fh;

my $intro = "\\begin{intro}\n\\end{intro}";

#Create schedule
my $datacopy = $data;

my $schedule ="I";

while($datacopy =~ m/(.*?)((?:Verse|Interlude|Chorus|Pre-Chorus|Bridge|Interlude|Intro|Outro) ?(\d+)?)(.*?)/gm)
{

  $schedule = $schedule . " -- " . $2;
  $schedule =~ s/Vers ?/V/g;
  $schedule =~ s/Interlude ?/Z/g;
  $schedule =~ s/Pre-Chorus ?/PC/g;
  $schedule =~ s/Chorus ?/R/g;
  $schedule =~ s/Intro ?/I/g;
  $schedule =~ s/Outro ?/O/g;
  $schedule =~ s/Bridge ?/B/g;
}

$schedule = "\\begin{schedule}\n$schedule\n\\end{schedule}";

print $schedule;

$data =~ s/^Vers ?(\d+)?\R(.*?)\R\R/\\begin{verse}\n$2\n\\end{verse}\n/msg;
$data =~ s/^Interlude ?(\d+)?\R(.*?)\R\R/\\begin{interlude}\n$2\n\\end{interlude}\n/msg;
$data =~ s/^Chorus ?(\d+)?\R(.*?)\R\R/\\begin{chorus}\n$2\n\\end{chorus}\n/msg;
$data =~ s/^Pre-Chorus ?(\d+)?\R(.*?)\R\R/\\begin{prechorus}\n$2\n\\end{prechorus}\n/msg;
$data =~ s/^Bridge ?(\d+)?\R(.*?)\R\R/\\begin{bridge}\n$2\n\\end{bridge}\n/msg;

$data =~ s/(.*?)\R(.*)CCLI-Liednummer .*\R(.*)\R(.*)\R.*\RCCLI-Lizenznummer .*/\\documentclass[]{leadsheet-modern}\n\n\\begin{document}\n\n\\begin{song}[]{title={$1},composer={$3}}\n\n$schedule\n\n$intro\n$2\n\\end{song}\n\\end{document}\n/msg;

$data =~ s/ \|/,/msg;

#while ($data =~ s/(\\begin{(?'part'verse|interlude|prechorus|chorus)}\R)(?!\\end{(?P=part)}|(?:.*)\\\\\R)(.*)\R/$1$2\\/gm) {
#}

open my $fh2, '>', $outputFile or die "error opening $outputFile: $!";

print $fh2 $data;
close $fh2;
